version: 2
updates:
  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "direct"
      - dependency-type: "development"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "chore(deps): "
    security-updates-only: true
    rebase-strategy: "auto"
