name: Deploy WTFe to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:  # This enables manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Ensure you're using v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Build WTFe
        run: yarn build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2  # Updated to v2 (works with GitHub Pages)

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy WTFe to GitHub Pages
        uses: actions/deploy-pages@v4  # Updated to v4
